/**
 * Backend compatibility tests for VC verification
 *
 * These tests verify that VCs generated by the Python backend can be
 * successfully verified using the JavaScript frontend verification code.
 *
 * IMPORTANT: These tests use the ACTUAL production functions from:
 * - didcheck/src/utils/vcValidation.js
 * - didcheck/src/utils/proofVerification.js
 *
 * This ensures we're testing the exact same code paths as production.
 *
 * Prerequisites:
 * 1. Run `pytest -m vc_compat` to generate fixtures
 * 2. Run `npm install` in this directory to install dependencies
 * 3. Run `npm test` to execute tests
 */

import { describe, test, expect, beforeAll, vi } from 'vitest'
import { readFileSync } from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'
import { testDocumentLoader } from './testDocumentLoader.js'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const FIXTURES_DIR = path.resolve(__dirname, '../../../tests/fixtures/vc_compat')

// Mock the documentLoader module to use our test loader instead of the production one
vi.mock('../../src/utils/documentLoader.js', () => ({
  documentLoader: testDocumentLoader
}))

// NOW import the production functions (after mocking documentLoader)
import { validateVCStructure, extractUidFromDID, extractVCId } from '../../src/utils/vcValidation.js'
import { verifyVCProof, canonicalizeVC } from '../../src/utils/proofVerification.js'

// Load manifest eagerly (during module load, not in beforeAll)
// This ensures test.each has access to it during test collection
const manifestPath = path.join(FIXTURES_DIR, 'manifest.json')
let manifest
try {
  manifest = JSON.parse(readFileSync(manifestPath, 'utf-8'))
} catch (error) {
  console.error(
    `Failed to load manifest.json. Make sure to run 'pytest -m vc_compat' first to generate fixtures.`
  )
  manifest = { vcs: [], did_documents: [] }
}

describe('VC Compatibility Tests - Using Production Code', () => {
  describe('DID Document Loading', () => {
    test('should load all division DID documents from fixtures', () => {
      expect(manifest.did_documents).toBeDefined()
      expect(manifest.did_documents.length).toBeGreaterThanOrEqual(2)

      for (const didDoc of manifest.did_documents) {
        const didPath = path.join(FIXTURES_DIR, didDoc.file)
        const didDocument = JSON.parse(readFileSync(didPath, 'utf-8'))

        // Verify DID document structure
        expect(didDocument.id).toBe(`did:web:did.amd.com:${didDoc.division}`)
        expect(didDocument['@context']).toBeDefined()
        expect(didDocument.verificationMethod).toBeDefined()
        expect(didDocument.verificationMethod.length).toBeGreaterThan(0)
        expect(didDocument.assertionMethod).toBeDefined()
      }
    })
  })

  describe('VC Structure Validation - Using validateVCStructure()', () => {
    test.each(manifest?.vcs || [])('should validate structure of $file', async ({ file }) => {
      const vcPath = path.join(FIXTURES_DIR, file)
      const credential = JSON.parse(readFileSync(vcPath, 'utf-8'))

      // Use the PRODUCTION validateVCStructure function
      const result = await validateVCStructure(credential)

      // All checks should pass
      expect(result.valid).toBe(true)
      expect(result.checks).toBeDefined()
      expect(result.checks.length).toBeGreaterThan(0)

      // Every check should pass
      for (const check of result.checks) {
        expect(check.passed).toBe(true)
      }

      // Should extract versionUid
      expect(result.versionUid).toBeDefined()
      expect(result.versionUid).toMatch(/^[0-9a-f-]+$/)
    })
  })

  describe('VC Cryptographic Verification - Using verifyVCProof()', () => {
    test.each(manifest?.vcs || [])('should verify proof of $file', async ({ file }) => {
      const vcPath = path.join(FIXTURES_DIR, file)
      const credential = JSON.parse(readFileSync(vcPath, 'utf-8'))

      // Use the PRODUCTION verifyVCProof function
      const result = await verifyVCProof(credential)

      // Log detailed error if verification fails
      if (!result.verified) {
        console.log(`\nVerification failed for ${file}:`)
        console.log('Error:', result.error)
        console.log('Verification Method:', credential.proof?.verificationMethod)
      }

      // Expect verification to succeed
      expect(result.verified).toBe(true)
      expect(result.error).toBeUndefined()

      // Should have details about the proof
      expect(result.details).toBeDefined()
      expect(result.details.proofType).toBe('DataIntegrityProof')
      expect(result.details.cryptosuite).toBe('eddsa-rdfc-2022')
      expect(result.details.verificationMethod).toBeDefined()
    })
  })

  describe('Canonicalization Comparison', () => {
    test.each(manifest?.vcs || [])('should match Python canonicalization for $file', async ({ file }) => {
      const vcPath = path.join(FIXTURES_DIR, file)
      const credential = JSON.parse(readFileSync(vcPath, 'utf-8'))

      // Get the basename without extension
      const basename = path.basename(file, '.json')

      // Canonicalize using JavaScript implementation
      const jsCanonical = await canonicalizeVC(credential)

      // Load the Python canonical N-Quads
      const pythonCanonicalPath = path.join(FIXTURES_DIR, 'canonical', `${basename}.nquads`)
      let pythonCanonical
      try {
        pythonCanonical = readFileSync(pythonCanonicalPath, 'utf-8')
      } catch (error) {
        throw new Error(
          `Python canonical file not found: ${pythonCanonicalPath}. ` +
          `Make sure to run 'pytest -m vc_compat' with the latest test code.`
        )
      }

      // Compare canonicalized forms
      // Normalize line endings and trim whitespace
      const jsNormalized = jsCanonical.trim().replace(/\r\n/g, '\n')
      const pythonNormalized = pythonCanonical.trim().replace(/\r\n/g, '\n')

      if (jsNormalized !== pythonNormalized) {
        console.log(`\nCanonicaliz ation mismatch for ${file}:`)
        console.log('JavaScript length:', jsNormalized.length)
        console.log('Python length:', pythonNormalized.length)
        console.log('\nFirst 500 chars of JS:', jsNormalized.substring(0, 500))
        console.log('\nFirst 500 chars of Python:', pythonNormalized.substring(0, 500))
      }

      expect(jsNormalized).toBe(pythonNormalized)
    })
  })

  describe('Helper Functions', () => {
    test('extractUidFromDID should extract UUID from AMD DIDs', () => {
      const did = 'did:web:did.amd.com:11111111-1111-1111-1111-111111111111'
      const uid = extractUidFromDID(did)
      expect(uid).toBe('11111111-1111-1111-1111-111111111111')
    })

    test('extractUidFromDID should return null for invalid DIDs', () => {
      expect(extractUidFromDID('')).toBeNull()
      expect(extractUidFromDID('not-a-did')).toBeNull()
      expect(extractUidFromDID('did:web:example.com:123')).toBeNull()
    })

    test('extractVCId should extract VC ID from fixture VCs', () => {
      // Load a fixture and test extractVCId
      const vcPath = path.join(FIXTURES_DIR, 'vcs/advisory_basic.json')
      const credential = JSON.parse(readFileSync(vcPath, 'utf-8'))

      const vcId = extractVCId(credential)
      expect(vcId).toBeDefined()
      expect(vcId).toMatch(/^[0-9a-f-]+$/)
    })
  })

  describe('End-to-End Validation - Full Production Pipeline', () => {
    test('advisory basic VC should pass all production validation', async () => {
      const vcPath = path.join(FIXTURES_DIR, 'vcs/advisory_basic.json')
      const credential = JSON.parse(readFileSync(vcPath, 'utf-8'))

      // Run the full validation using production code
      const result = await validateVCStructure(credential)

      // Log the result for debugging
      if (!result.valid) {
        console.log('Validation failed for advisory_basic.json:')
        console.log('Checks:', JSON.stringify(result.checks, null, 2))
      }

      expect(result.valid).toBe(true)
      expect(result.versionUid).toBeDefined()

      // Verify each individual check
      const checkNames = result.checks.map(c => c.name)
      expect(checkNames).toContain('Type Field')
      expect(checkNames).toContain('Issuer')
      expect(checkNames).toContain('Credential Subject ID')
      expect(checkNames).toContain('Version UID')
      expect(checkNames).toContain('Proof Verification')

      // All checks should pass
      expect(result.checks.every(c => c.passed)).toBe(true)
    })

    test('EPDW VC with metadata should pass all production validation', async () => {
      const vcPath = path.join(FIXTURES_DIR, 'vcs/epdw_with_metadata.json')
      const credential = JSON.parse(readFileSync(vcPath, 'utf-8'))

      const result = await validateVCStructure(credential)

      expect(result.valid).toBe(true)
      expect(credential.credentialSubject.artefactMetadata).toBeDefined()
      expect(credential.credentialSubject.artefactMetadata.benchmark_name).toBe('SPEC CPU 2017')
    })

    test('VC with hash should pass all production validation', async () => {
      const vcPath = path.join(FIXTURES_DIR, 'vcs/advisory_with_hash.json')
      const credential = JSON.parse(readFileSync(vcPath, 'utf-8'))

      const result = await validateVCStructure(credential)

      expect(result.valid).toBe(true)
      expect(credential.credentialSubject.artefactHash).toBe('QmYwAPJzv5CZsnA625s3Xf2nemtYgPpHdWEz79ojWnPbdG')
    })

    test('VC with provenance should pass all production validation', async () => {
      const vcPath = path.join(FIXTURES_DIR, 'vcs/epdw_with_provenance.json')
      const credential = JSON.parse(readFileSync(vcPath, 'utf-8'))

      const result = await validateVCStructure(credential)

      expect(result.valid).toBe(true)
      expect(credential.credentialSubject.provenance).toBeDefined()
      expect(Array.isArray(credential.credentialSubject.provenance)).toBe(true)
      expect(credential.credentialSubject.provenance.length).toBeGreaterThan(0)
    })

    test('complex VC with all fields should pass all production validation', async () => {
      const vcPath = path.join(FIXTURES_DIR, 'vcs/advisory_complex.json')
      const credential = JSON.parse(readFileSync(vcPath, 'utf-8'))

      const result = await validateVCStructure(credential)

      expect(result.valid).toBe(true)
      expect(credential.credentialSubject.artefactType).toBe('security-report')
      expect(credential.credentialSubject.artefactHash).toBeDefined()
      expect(credential.credentialSubject.artefactMetadata).toBeDefined()
      expect(credential.credentialSubject.artefactMetadata.severity).toBe('high')
    })

    test('complex VC with tampered proofValue should fail validation', async () => {
      const vcPath = path.join(FIXTURES_DIR, 'vcs/advisory_complex.json')
      const credential = JSON.parse(readFileSync(vcPath, 'utf-8'))

      // Tamper with the proofValue field.
      credential.proof.proofValue = credential.proof.proofValue.replace(/u(......)/, (m, g1) => "uH8qkWL")

      const result = await validateVCStructure(credential)

      expect(result.valid).toBe(false)
      for (const check of result.checks) {
        if (check.name == "Proof Verification") {
          expect(check.passed).toBe(false)
        }
      }
    })

    test('complex VC with tampered artefactHash should fail validation', async () => {
      const vcPath = path.join(FIXTURES_DIR, 'vcs/advisory_complex.json')
      const credential = JSON.parse(readFileSync(vcPath, 'utf-8'))

      // Tamper with the artefactHash field.
      credential.credentialSubject.artefactHash = credential.credentialSubject.artefactHash.substr(0, 40) + "rQdVrF"

      const result = await validateVCStructure(credential)

      expect(result.valid).toBe(false)
      for (const check of result.checks) {
        if (check.name == "Proof Verification") {
          expect(check.passed).toBe(false)
        }
      }
    })

    test('complex VC with tampered artefactMetadata should fail validation', async () => {
      const vcPath = path.join(FIXTURES_DIR, 'vcs/advisory_complex.json')
      const credential = JSON.parse(readFileSync(vcPath, 'utf-8'))

      // Tamper with the artefactMetadata field.
      delete(credential.credentialSubject.artefactMetadata.severity);

      const result = await validateVCStructure(credential)

      expect(result.valid).toBe(false)
      for (const check of result.checks) {
        if (check.name == "Proof Verification") {
          expect(check.passed).toBe(false)
        }
      }
    })
  })

  describe('Individual Check Results', () => {
    test('should provide detailed check results for each validation', async () => {
      const vcPath = path.join(FIXTURES_DIR, 'vcs/advisory_basic.json')
      const credential = JSON.parse(readFileSync(vcPath, 'utf-8'))

      const result = await validateVCStructure(credential)

      // Verify we get detailed results for each check
      expect(result.checks.length).toBe(5) // 5 checks total

      for (const check of result.checks) {
        expect(check.name).toBeDefined()
        expect(check.passed).toBe(true)
        expect(check.message).toBeDefined()
        // Some checks may have a value field
      }
    })
  })

  describe('Production Error Handling', () => {
    test('verifyVCProof should handle missing proof gracefully', async () => {
      const invalidVC = {
        '@context': ['https://www.w3.org/2018/credentials/v1'],
        type: ['VerifiableCredential'],
        issuer: 'did:web:did.amd.com:advisory',
        credentialSubject: { id: 'did:web:did.amd.com:test' }
        // Missing proof
      }

      const result = await verifyVCProof(invalidVC)

      expect(result.verified).toBe(false)
      expect(result.error).toBeDefined()
      expect(result.error).toContain('no proof')
    })

    test('validateVCStructure should detect missing type field', async () => {
      const invalidVC = {
        '@context': ['https://www.w3.org/2018/credentials/v1'],
        // Missing type
        issuer: 'did:web:did.amd.com:advisory',
        credentialSubject: { id: 'did:web:did.amd.com:test' }
      }

      const result = await validateVCStructure(invalidVC)

      expect(result.valid).toBe(false)
      const typeCheck = result.checks.find(c => c.name === 'Type Field')
      expect(typeCheck).toBeDefined()
      expect(typeCheck.passed).toBe(false)
    })

    test('validateVCStructure should detect invalid issuer', async () => {
      const invalidVC = {
        '@context': ['https://www.w3.org/2018/credentials/v1'],
        type: ['VerifiableCredential', 'DigitalArtefactCredential'],
        issuer: 'did:web:example.com:not-amd', // Wrong issuer
        credentialSubject: {
          id: 'did:web:did.amd.com:11111111-1111-1111-1111-111111111111',
          versionUid: '22222222-2222-2222-2222-222222222222'
        }
      }

      const result = await validateVCStructure(invalidVC)

      expect(result.valid).toBe(false)
      const issuerCheck = result.checks.find(c => c.name === 'Issuer')
      expect(issuerCheck).toBeDefined()
      expect(issuerCheck.passed).toBe(false)
      expect(issuerCheck.message).toContain('did:web:did.amd.com')
    })
  })
})
