import logging
from typing import Any
from uuid import uuid4

from fastapi import APIRouter
from pydantic import BaseModel, Field

from app.routers.basetypes import (
    AMDWebDID,
    ArtefactFieldsMixin,
    PathUUID,
    UUIDString,
    did_from_uuid,
)
from app.routers.dependencies import AdvisoryTokenDep, APITokenDep401Response, DIDServiceDep
from app.routers.responses import bad_request_response, conflict_response, not_found_response
from app.services.did_service import ArtefactInput

_ADVISORY_DIVISION = "advisory"

router = APIRouter(tags=["Advisory API"], prefix="/advisory")
logger = logging.getLogger("advisory_api")

_example_random_uuid = f"{uuid4()}"

class RecordReportRequest(ArtefactFieldsMixin):
    artefact_id: UUIDString = Field(
        ...,  # Required
        description="Globally unique ID of this object (must be a valid UUID)",
        json_schema_extra={"example": _example_random_uuid},
        examples=[_example_random_uuid],
    )

    # Override artefact_metadata with more specific description
    artefact_metadata: dict[str, Any] | None = Field(
        default=None,
        alias="artefact_metadata",
        description="An object with properties set by the caller (corresponds to metadata about the artefact)",
        json_schema_extra={"example": {"filename": "cca-report-123761827584.xsls", "service": "cca"}},
    )

class RecordReportResponse(BaseModel):
    artefact_did: AMDWebDID = Field(
        description="""The DID generated by the system for the artefact. This may
        not be unique if the same artefact_id is reused multiple times (each time
        generates a new internal version of the DID).""",
        examples=[f"did:web:did.amd.com:{_example_random_uuid}"],
    )
    version_did: AMDWebDID = Field(
        description="""The DID generated for the specific version created by the request.""",
        examples=["did:web:did.amd.com:b8ff3b79-863f-4fa9-84ba-0067663f2b04"],
    )
    version: int = Field(
        description="""The version number of the DID, if multiple versions of the same
        artefact were created. Starts at 1.""",
        examples=[1, 18],
    )


@router.post("/record_report", responses={**APITokenDep401Response, **bad_request_response(), **conflict_response(_ADVISORY_DIVISION)})
async def record_report(request: RecordReportRequest, api_token: AdvisoryTokenDep, did_svc: DIDServiceDep) -> RecordReportResponse:
    """Record an advisory report as a DID.

    Creates a new Digital Artefact record or a new version of an existing one.
    If the artefact_id already exists, the request must include at least one
    change to artefact_hash, artefact_metadata, or provenance - otherwise a
    400 Bad Request error is returned.
    """

    # Build artefact input from request
    artefact_input = ArtefactInput(
        external_uid=request.artefact_id,
        division=_ADVISORY_DIVISION,
        artefact_hash=request.artefact_hash,
        artefact_metadata=request.artefact_metadata,
        artefact_type="report",  # Advisory reports are always type "report"
        backlink=request.backlink,
        provenance=request.provenance,
        update_message=request.update_message,
        updated_by=request.updated_by,
    )

    # Upsert the artefact
    record = did_svc.upsert_artefact(artefact_input)

    return RecordReportResponse(
        artefact_did=did_from_uuid(record.external_uid),
        version_did=did_from_uuid(record.version_uid),
        version=record.version,
    )

@router.get("/did.json")
async def advisory_did(did_svc: DIDServiceDep):
    """Return the DID document that corresponds to the advisory division.

    This DID document contains the keys that are used to verify digital artefacts
    associated with the advisory division.

    Returns:
        JSON-LD DID Document.
    """
    return did_svc.division_did_doc(_ADVISORY_DIVISION)


@router.get("/{uid}/vc.json", responses={**APITokenDep401Response, **not_found_response()})
async def artefact_vc(
    uid: PathUUID,
    api_token: AdvisoryTokenDep,
    did_svc: DIDServiceDep,):
    """Return a Verifiable Credential with proofs for a Digital Artefact."""
    return did_svc.issue_artefact_vc(division=_ADVISORY_DIVISION, uid=uid)
