import logging
from typing import Any
from uuid import uuid4

from fastapi import APIRouter
from pydantic import BaseModel, Field

from app.routers.basetypes import (
    AMDEmail,
    AMDWebDID,
    ArtefactFieldsMixin,
    CanonicalizedUUID,
    Multihash,
    PathUUID,
    UUIDString,
    artefact_type_from_str,
    did_from_uuid,
    division_from_str,
)
from app.routers.dependencies import AdvisoryTokenDep, APITokenDep401Response, DIDServiceDep
from app.routers.responses import bad_request_response, conflict_response, not_found_response
from app.services.did_service import ArtefactInput
from app.services.exceptions import RecommendationNotFoundError

_ADVISORY_DIVISION = "advisory"

router = APIRouter(tags=["Advisory API"], prefix="/advisory")
logger = logging.getLogger("advisory_api")

_example_random_uuid = f"{uuid4()}"

class RecordRecommendationRequest(ArtefactFieldsMixin):
    artefact_uid: UUIDString = Field(
        ...,  # Required
        description="Globally unique ID of this recommendation (must be a valid UUID)",
        json_schema_extra={"example": _example_random_uuid},
        examples=[_example_random_uuid],
    )

    # Override artefact_metadata with more specific description
    artefact_metadata: dict[str, Any] | None = Field(
        default=None,
        alias="artefact_metadata",
        description="An object with properties set by the caller (corresponds to metadata about the artefact)",
        json_schema_extra={"example": {"platform": "cloud", "provider": "AWS"}},
    )


class RecordRecommendationResponse(BaseModel):
    artefact_did: AMDWebDID = Field(
        description="""The DID generated by the system for the artefact. This may
        not be unique if the same artefact_id is reused multiple times (each time
        generates a new internal version of the DID).""",
        examples=[f"did:web:did.amd.com:{_example_random_uuid}"],
    )
    version_did: AMDWebDID = Field(
        description="""The DID generated for the specific version created by the request.""",
        examples=["did:web:did.amd.com:b8ff3b79-863f-4fa9-84ba-0067663f2b04"],
    )
    version: int = Field(
        description="""The version number of the DID, if multiple versions of the same
        artefact were created. Starts at 1.""",
        examples=[1, 18],
    )


@router.post("/record_recommendation", responses={**APITokenDep401Response, **bad_request_response(), **conflict_response(_ADVISORY_DIVISION)})
async def record_recommendation(request: RecordRecommendationRequest, api_token: AdvisoryTokenDep, did_svc: DIDServiceDep) -> RecordRecommendationResponse:
    """Record an advisory recommendation as a DID.

    Creates a new Digital Artefact record of type 'recommendation' or a new version of an existing one.
    If the artefact_uid already exists, the request must include at least one
    change to artefact_hash, artefact_metadata, or provenance - otherwise a
    400 Bad Request error is returned.
    """

    # Build artefact input from request
    artefact_input = ArtefactInput(
        external_uid=request.artefact_uid,
        division=_ADVISORY_DIVISION,
        artefact_hash=request.artefact_hash,
        artefact_metadata=request.artefact_metadata,
        artefact_type="recommendation",  # Advisory recommendations are always type "recommendation"
        backlink=request.backlink,
        provenance=request.provenance,
        update_message=request.update_message,
        updated_by=request.updated_by,
    )

    # Upsert the artefact
    record = did_svc.upsert_artefact(artefact_input)

    return RecordRecommendationResponse(
        artefact_did=did_from_uuid(record.external_uid),
        version_did=did_from_uuid(record.version_uid),
        version=record.version,
    )


class RecordReportRequest(BaseModel):
    report_uid: UUIDString = Field(
        ...,  # Required
        description="Globally unique ID of this report (must be a valid UUID)",
        json_schema_extra={"example": _example_random_uuid},
        examples=[_example_random_uuid],
    )

    recommendation_uid: CanonicalizedUUID = Field(
        ...,  # Required
        description="UUID or DID of a recommendation artefact that this report is based on",
        json_schema_extra={"example": _example_random_uuid},
        examples=[_example_random_uuid],
    )

    artefact_hash: Multihash | None = Field(
        default=None,
        description=(
            "A multihash string for the hash of the artefact blob (optional). "
            "Currently, the only allowed format is a Base58-Bitcoin encoded string "
            "containing a SHA-256 hash (i.e. the result of the function `Base58Bitcoin(Multihash(SHA256(data)))`)"
        ),
        json_schema_extra={"example": "QmYwAPJzv5CZsnAzt8auVZRn8x5M3kN1p6yZR2oG7wJGDk"},
    )

    artefact_metadata: dict[str, Any] | None = Field(
        default=None,
        description="An object with properties set by the caller (corresponds to metadata about the artefact)",
        json_schema_extra={"example": {"filename": "cca-report-123761827584.xsls", "service": "cca"}},
    )

    backlink: str | None = Field(
        default=None,
        description=(
            "Optional URL back to the object in the originating system. This may "
            "be used by the DIDCheck UI to link back to the resource in the originating "
            "app. Examples: `https://epycdatawarehouse.amd.com/benchmark/6bac3606-f73c-43fe-9084-32292ee5166b`, "
            "`https://eia-prod.amd.com/portfolio/6bac3606-f73c-43fe-9084-32292ee5166b`"
        ),
        json_schema_extra={"example": "https://example.com/resource/123"},
    )

    update_message: str | None = Field(
        default=None,
        description="Optional message describing this update",
        json_schema_extra={"example": "Updated with new data"},
    )

    updated_by: AMDEmail = Field(
        default=None,
        description="Optional AMD email of the person who made this update",
        json_schema_extra={"example": "user@amd.com"},
    )


class RecordReportResponse(BaseModel):
    artefact_did: AMDWebDID = Field(
        description="""The DID generated by the system for the artefact. This may
        not be unique if the same artefact_id is reused multiple times (each time
        generates a new internal version of the DID).""",
        examples=[f"did:web:did.amd.com:{_example_random_uuid}"],
    )
    version_did: AMDWebDID = Field(
        description="""The DID generated for the specific version created by the request.""",
        examples=["did:web:did.amd.com:b8ff3b79-863f-4fa9-84ba-0067663f2b04"],
    )
    version: int = Field(
        description="""The version number of the DID, if multiple versions of the same
        artefact were created. Starts at 1.""",
        examples=[1, 18],
    )


@router.post("/record_report", responses={**APITokenDep401Response, **bad_request_response(), **conflict_response(_ADVISORY_DIVISION)})
async def record_report(request: RecordReportRequest, api_token: AdvisoryTokenDep, did_svc: DIDServiceDep) -> RecordReportResponse:
    """Record an advisory report as a DID.

    Creates a new Digital Artefact record or a new version of an existing one.
    The report must reference a valid recommendation artefact via recommendation_uid.
    If the artefact_id already exists, the request must include at least one
    change to artefact_hash, artefact_metadata, or provenance - otherwise a
    400 Bad Request error is returned.
    """

    # Validate that recommendation_uid exists and is of type "recommendation" in advisory division
    recommendation = did_svc.find_artefact_by_uid_and_type(
        uid=request.recommendation_uid,
        division=division_from_str(_ADVISORY_DIVISION),
        artefact_type=artefact_type_from_str("recommendation")
    )

    if recommendation is None:
        raise RecommendationNotFoundError(request.recommendation_uid)

    # Build artefact input from request with recommendation_uid as provenance
    artefact_input = ArtefactInput(
        external_uid=request.report_uid,
        division=_ADVISORY_DIVISION,
        artefact_hash=request.artefact_hash,
        artefact_metadata=request.artefact_metadata,
        artefact_type="report",  # Advisory reports are always type "report"
        backlink=request.backlink,
        provenance=[request.recommendation_uid],  # Set provenance to the recommendation
        update_message=request.update_message,
        updated_by=request.updated_by,
    )

    # Upsert the artefact
    record = did_svc.upsert_artefact(artefact_input)

    return RecordReportResponse(
        artefact_did=did_from_uuid(record.external_uid),
        version_did=did_from_uuid(record.version_uid),
        version=record.version,
    )

@router.get("/did.json")
async def advisory_did(did_svc: DIDServiceDep):
    """Return the DID document that corresponds to the advisory division.

    This DID document contains the keys that are used to verify digital artefacts
    associated with the advisory division.

    Returns:
        JSON-LD DID Document.
    """
    return did_svc.division_did_doc(_ADVISORY_DIVISION)


@router.get("/{uid}/vc.json", responses={**APITokenDep401Response, **not_found_response()})
async def artefact_vc(
    uid: PathUUID,
    api_token: AdvisoryTokenDep,
    did_svc: DIDServiceDep,):
    """Return a Verifiable Credential with proofs for a Digital Artefact."""
    return did_svc.issue_artefact_vc(division=_ADVISORY_DIVISION, uid=uid)
