from fastapi import APIRouter
from pydantic import BaseModel, Field
from typing import Any
import logging, uuid
from app.routers.basetypes import UUIDString, DIDString
from app.routers.dependencies import APITokenDep


router = APIRouter(tags=["Advisory API"], prefix="/advisory")
logger = logging.getLogger("advisory_api")

class RecordReportRequest(BaseModel):
    artefact_id: UUIDString = Field(
        description="Globally unique ID of this object (must be a valid UUID)",
        examples=["2cacad4f-63ab-4668-9db7-7fc2538caa8c"],
    )
    artefact_hash: str = Field(
        alias="artefactHash",
        description="A multihash string for the hash of the artefact blob",
        examples=["QmYwAPJzv5CZsnAzt8auVZRn8x5M3kN1p6yZR2oG7wJGDk"],
    )
    artefact_metadata: dict[str, Any] = Field(
        default_factory=dict,
        alias="artefactMetadata",
        description="An object with properties set by the caller (corresponds to metadata about the artefact)",
        examples=[{"filename": "cca-report-123761827584.xsls", "service": "cca"}],
    )

class RecordReportResponse(BaseModel):
    artefact_did: DIDString = Field(
        description="""The DID generated by the system for the artefact. This may
        not be unique if the same artefact_id is reused multiple times (each time
        generates a new internal version of the DID).""",
        examples=["did:did:amd:com:advisory:2cacad4f-63ab-4668-9db7-7fc2538caa8c"],
    )
    version_did: DIDString = Field(
        description="""The DID generated for the specific version created by the request.""",
        examples=["did:did:amd:com:advisory:b8ff3b79-863f-4fa9-84ba-0067663f2b04"],
    )
    version: int = Field(
        description="""The version number of the DID, if multiple versions of the same
        artefact were created. Starts at 1.""",
        examples=[1, 18],
    )


@router.post("/record_report")
async def record_report(request: RecordReportRequest, api_token: APITokenDep) -> RecordReportResponse:
    """Record an advisory report as a DID."""

    # api_token contains the validated token string if needed
    # TODO: Implement actual logic to generate/store DIDs
    artefact_did = f"did:amd:com:advisory:{request.artefact_id}"
    version_did = f"did:amd:com:advisory:{uuid.uuid4()}"

    return RecordReportResponse(
        artefact_did=artefact_did,
        version_did=version_did,
        version=1,
    )
