from uuid import uuid4
from fastapi import APIRouter, Path
from pydantic import BaseModel, Field
from typing import Annotated, Any, Optional
import logging
from app.routers.basetypes import AMDWebDID, CanonicalizedUUID, DIDOrUUIDList, Multihash, UUIDString, did_from_uuid
from app.routers.dependencies import AdvisoryTokenDep, APITokenDep401Response, DIDServiceDep
from app.services.did_service import ArtefactInput

_ADVISORY_DIVISION = "advisory"

router = APIRouter(tags=["Advisory API"], prefix="/advisory")
logger = logging.getLogger("advisory_api")

_example_random_uuid = f"{uuid4()}"

class RecordReportRequest(BaseModel):
    artefact_id: UUIDString = Field(
        ...,  # Required
        description="Globally unique ID of this object (must be a valid UUID)",
        json_schema_extra={"example": _example_random_uuid},
        examples=[_example_random_uuid],
    )
    artefact_hash: Optional[Multihash] = Field(
        default=None,
        alias="artefact_hash",
        description="A multihash string for the hash of the artefact blob (optional)",
        json_schema_extra={"example": "QmYwAPJzv5CZsnAzt8auVZRn8x5M3kN1p6yZR2oG7wJGDk"},
    )
    artefact_metadata: Optional[dict[str, Any]] = Field(
        default=None,
        alias="artefact_metadata",
        description="An object with properties set by the caller (corresponds to metadata about the artefact)",
        json_schema_extra={"example": {"filename": "cca-report-123761827584.xsls", "service": "cca"}},
    )
    provenance: Optional[DIDOrUUIDList] = Field(
        default=None,
        description="List of provenance identifiers (DIDs or UUIDs). Each item is validated and "
                    "canonicalized to UUID format. Items must be unique after canonicalization."
                    "For example: `[\"did:web:did.amd.com:b8ff3b79-863f-4fa9-84ba-0067663f2b04\", \"b8ff3b79-863f-4fa9-84ba-0067663f2b04\"]`",
        json_schema_extra={"example": []},
    )

class RecordReportResponse(BaseModel):
    artefact_did: AMDWebDID = Field(
        description="""The DID generated by the system for the artefact. This may
        not be unique if the same artefact_id is reused multiple times (each time
        generates a new internal version of the DID).""",
        examples=[f"did:web:did.amd.com:{_example_random_uuid}"],
    )
    version_did: AMDWebDID = Field(
        description="""The DID generated for the specific version created by the request.""",
        examples=["did:web:did.amd.com:b8ff3b79-863f-4fa9-84ba-0067663f2b04"],
    )
    version: int = Field(
        description="""The version number of the DID, if multiple versions of the same
        artefact were created. Starts at 1.""",
        examples=[1, 18],
    )


# Response documentation for 400 Bad Request errors
BadRequestResponse = {
    400: {
        "description": "Bad Request: Invalid input or no changes detected",
        "content": {
            "application/json": {
                "examples": {
                    "no_changes": {
                        "summary": "No changes detected",
                        "value": {
                            "detail": (
                                "No changes detected for artefact 'b8ff3b79-863f-4fa9-84ba-0067663f2b04'. "
                                "A new version requires changes to at least one of: "
                                "artefact_hash, artefact_metadata, or provenance."
                            )
                        }
                    },
                    "duplicate_provenance": {
                        "summary": "Duplicated item in provenance list",
                        "value": {
                            "detail": (
                                "Duplicate identifiers found after canonicalization. "
                                "Each provenance item must be unique."
                            )
                        }
                    }
                }
            }
        }
    }
}

# Response documentation for 409 Conflict errors
ConflictResponse = {
    409: {
        "description": "Conflict error: Division mismatch or version conflict",
        "content": {
            "application/json": {
                "examples": {
                    "division_mismatch": {
                        "summary": "Division mismatch",
                        "value": {"detail": "Division mismatch: existing division is 'advisory', but attempted to set 'other'"}
                    },
                    "version_conflict": {
                        "summary": "Version conflict",
                        "value": {"detail": "Version conflict: version 2 already exists"}
                    },
                    "provenance_not_found": {
                        "summary": "Provenance item not found",
                        "value": {"detail": "Provenance item not found: 2cacad4f-63ab-4668-9db7-7fc2538caa8c"}
                    }
                }
            }
        }
    }
}


@router.post("/record_report", responses={**APITokenDep401Response, **BadRequestResponse, **ConflictResponse})
async def record_report(request: RecordReportRequest, api_token: AdvisoryTokenDep, did_svc: DIDServiceDep) -> RecordReportResponse:
    """Record an advisory report as a DID.

    Creates a new Digital Artefact record or a new version of an existing one.
    If the artefact_id already exists, the request must include at least one
    change to artefact_hash, artefact_metadata, or provenance - otherwise a
    400 Bad Request error is returned.
    """

    # Build artefact input from request
    artefact_input = ArtefactInput(
        external_uid=request.artefact_id,
        division=_ADVISORY_DIVISION,
        artefact_hash=request.artefact_hash,
        artefact_metadata=request.artefact_metadata,
        provenance=request.provenance,
    )

    # Upsert the artefact
    record = did_svc.upsert_artefact(artefact_input)

    return RecordReportResponse(
        artefact_did=did_from_uuid(record.external_uid),
        version_did=did_from_uuid(record.version_uid),
        version=record.version,
    )

@router.get("/did.json")
async def advisory_DID(did_svc: DIDServiceDep):
    """Return the DID document that corresponds to the advisory division.

    This DID document contains the keys that are used to verify digital artefacts
    associated with the advisory division.

    Returns:
        JSON-LD DID Document.
    """
    return did_svc.division_did_doc(_ADVISORY_DIVISION)

PathUUID = Annotated[CanonicalizedUUID, Path(
    description="The UID or DID of the artefact to retrieve the Verifiable Credential for",
    openapi_examples={"normal":{"value":_example_random_uuid}},
)]

@router.get("/{uid}/vc.json", responses={**APITokenDep401Response})
async def artefact_vc(
    uid: PathUUID,
    api_token: AdvisoryTokenDep,
    did_svc: DIDServiceDep,):
    """Return a Verifiable Credential with proofs for a Digital Artefact."""
    return did_svc.issue_artefact_vc(division=_ADVISORY_DIVISION, uid=uid)
