"""
Routers for the "demo division" API - a test API only enabled on dev/staging
environments for quick check of the DIDSvc functionality.
"""

import logging
from uuid import uuid4

from fastapi import APIRouter
from pydantic import BaseModel, Field

from app.routers.basetypes import (
    AMDWebDID,
    ArtefactFieldsMixin,
    ArtefactTypeStr,
    UUIDString,
    did_from_uuid,
)
from app.routers.dependencies import APITokenDep401Response, DemoDivTokenDep, DIDServiceDep
from app.routers.responses import bad_request_response, conflict_response
from app.services.did_service import ArtefactInput

_DEMO_DIVISION = "demodivision"

router = APIRouter(tags=["Demo Division API"], prefix="/demodiv")
logger = logging.getLogger("demodivision")

_example_random_uuid = f"{uuid4()}"

class RecordArtefactRequest(ArtefactFieldsMixin):
    external_uid: UUIDString = Field(
        ...,  # Required
        description="Globally unique ID of this artefact (must be a valid UUID)",
        json_schema_extra={"example": _example_random_uuid},
        examples=[_example_random_uuid],
    )

    artefact_type: ArtefactTypeStr = Field(
        ...,  # Required
        description="String describing the type of the artefact (division-specific).",
        examples=["report", "benchmark"],
    )


class RecordArtefactResponse(BaseModel):
    artefact_did: AMDWebDID = Field(
        description="""The DID generated by the system for the artefact. This may
        not be unique if the same external_uid is reused multiple times (each time
        generates a new internal version of the DID).""",
        examples=[f"did:web:did.amd.com:{_example_random_uuid}"],
    )
    version_did: AMDWebDID = Field(
        description="""The DID generated for the specific version created by the request.""",
        examples=["did:web:did.amd.com:b8ff3b79-863f-4fa9-84ba-0067663f2b04"],
    )
    version: int = Field(
        description="""The version number of the DID, if multiple versions of the same
        artefact were created. Starts at 1.""",
        examples=[1, 18],
    )


@router.post("/record_artefact", responses={**APITokenDep401Response, **bad_request_response(), **conflict_response(_DEMO_DIVISION)})
async def record_artefact(request: RecordArtefactRequest, api_token: DemoDivTokenDep, did_svc: DIDServiceDep) -> RecordArtefactResponse:
    """Record an artefact created by the demo division.

    This is a generic demo API for testing during DIDSvc development. The "Demo Division"
    is free to create any artefact types using any schema.

    Actual AMD divisions **MUST NOT** use this endpoint for integration - this API
    is only provided for internal DIDSvc testing. This API is generally not
    enabled in production deployments of the service.
    """

    # Build artefact input from request
    artefact_input = ArtefactInput(
        external_uid=request.external_uid,
        division=_DEMO_DIVISION,
        artefact_hash=request.artefact_hash,
        artefact_metadata=request.artefact_metadata,
        artefact_type=request.artefact_type,
        backlink=request.backlink,
        provenance=request.provenance,
        update_message=request.update_message,
        updated_by=request.updated_by,
    )

    # Upsert the artefact
    record = did_svc.upsert_artefact(artefact_input)

    return RecordArtefactResponse(
        artefact_did=did_from_uuid(record.external_uid),
        version_did=did_from_uuid(record.version_uid),
        version=record.version,
    )

@router.get("/did.json")
async def demodiv_did(did_svc: DIDServiceDep):
    """Return the DID document that corresponds to the demo division.

    This DID document contains the keys that are used to verify digital artefacts
    associated with the advisory division.

    Returns:
        JSON-LD DID Document.
    """
    return did_svc.division_did_doc(_DEMO_DIVISION)
