# syntax=docker/dockerfile:1

# This is the Dockerfile that builds a production DIDCheck image. It builds the
# frontend code in a node image, then copies the results over to a minimal nginx
# image.

# Stage 1: Build the Vite/Vue app
FROM node:24-alpine AS builder

# Set working directory
WORKDIR /app

# Copy all code
COPY didcheck didcheck
COPY contexts contexts

# Move into the didcheck app folder.
WORKDIR /app/didcheck

# Install dependencies
RUN npm ci

# Build for production
RUN npm run build

# Stage 2: Serve with a lightweight web server
FROM nginx:1.29.6-alpine3.23-slim

# Remove default nginx static assets
RUN rm -rf /usr/share/nginx/html/*

# Copy built files from builder
COPY --from=builder /app/didcheck/dist /usr/share/nginx/html

# nginx.conf is setup in the approriate docker-compose file.

# Expose port 80
EXPOSE 80

# Start nginx
CMD ["nginx", "-g", "daemon off;"]
