version: "3.9"

services:
  api:
    container_name: didsvc-api
    build:
      context: ..
      dockerfile: deployment/Dockerfile
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    env_file:
      - ../.env
    restart: always
    expose:
      - "8000"   # private, nginx will access this

  nginx:
    image: nginx:1.25-alpine
    container_name: didsvc-nginx
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - api
    ports:
      - "80:80"
      - "443:443"
