version: "3.9"

services:
  app:
    container_name: did-app
    build:
      context: ..
      dockerfile: deployment/Dockerfile
    image: did-microservice:latest
    restart: always
    env_file:
      - ../.env
    expose:
      - "45603"
    networks:
      - private_net

  worker:
    container_name: did-worker
    build:
      context: ..
      dockerfile: deployment/Dockerfile
    image: did-microservice:latest
    restart: always
    command: celery -A celery_worker.celery_app worker --loglevel=info
    env_file:
      - ../.env
    networks:
      - private_net

  nginx:
    container_name: did-nginx
    build:
      context: ./nginx
    restart: always
    ports:
      - "443:443"
    volumes:
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - app
    networks:
      - private_net

networks:
  private_net:
    driver: bridge

