[loggers]
keys=root,uvicorn,uvicorn.error,uvicorn.access,fastapi,insane

[handlers]
keys=console

[formatters]
keys=fmt

[filters]
keys=requestip

[logger_root]
level=DEBUG
handlers=console

[logger_uvicorn]
level=DEBUG
handlers=console
qualname=uvicorn

[logger_uvicorn.error]
level=DEBUG
handlers=console
qualname=uvicorn.error

[logger_uvicorn.access]
level=DEBUG
handlers=console
qualname=uvicorn.access

[logger_fastapi]
level=DEBUG
handlers=console
qualname=fastapi

[logger_insane]
level=DEBUG
handlers=console
qualname=insane

[handler_console]
class=StreamHandler
level=DEBUG
formatter=fmt
args=(sys.stdout,)
filters=requestip

[filter_requestip]
#()=request_ip_filter.RequestIPFilter

[formatter_fmt]
format=%(asctime)s - %(name)s - %(levelname)s - %(message)s

[logger_pymongo]
level = WARNING
handlers =
qualname = pymongo
propagate = 0

[logger_pymongo_topology]
level = ERROR
handlers =
qualname = pymongo.topology
propagate = 0

[logger_pymongo_connection]
level = ERROR
handlers =
qualname = pymongo.connection
propagate = 0

[logger_pymongo_heartbeat]
level = ERROR
handlers =
qualname = pymongo.heartbeat
propagate = 0

